import express from "express";
import jwt from "jsonwebtoken";
import Sponsorship from "../models/Sponsorship.js";
import Sponsor from "../models/Sponsor.js";
import Student from "../models/Student.js";

const router = express.Router();

// Minimal student auth specific to Student tokens generated by studentAuthRoutes
async function requireStudent(req, res, next) {
  try {
    const token = req.header("Authorization")?.replace("Bearer ", "");
    if (!token) return res.status(401).json({ message: "No token" });
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    if (decoded.role !== "STUDENT") return res.status(403).json({ message: "Not a student token" });
    const me = await Student.findById(decoded.sub);
    if (!me) return res.status(404).json({ message: "Student not found" });
    req.student = me;
    next();
  } catch (_) {
    res.status(401).json({ message: "Invalid token" });
  }
}

// GET /api/student/sponsorships - list sponsorships for the logged-in student
router.get("/student/sponsorships", requireStudent, async (req, res) => {
  try {
    const list = await Sponsorship.find({ student: req.student._id })
      .populate({ path: "sponsor", select: "name tier logoUrl" })
      .sort({ createdAt: -1 })
      .lean();
    const total = list.reduce((sum, s) => sum + (Number(s.amount) || 0), 0);
    res.json({ sponsorships: list, total, currency: list[0]?.currency || "INR" });
  } catch (_) {
    res.status(500).json({ message: "Failed to load sponsors" });
  }
});

// Public: GET /api/sponsors - list active sponsors with optional search
router.get("/sponsors", async (req, res) => {
  try {
    const { q = "", limit = 10 } = req.query || {};
    const filter = { active: true };
    if (q && String(q).trim()) {
      filter.$text = { $search: String(q).trim() };
    }
    const sponsors = await Sponsor.find(filter)
      .sort({ tier: 1, createdAt: -1 })
      .limit(Math.max(1, Math.min(50, Number(limit) || 10)))
      .select("name tier logoUrl website description")
      .lean();
    res.json({ sponsors });
  } catch (_) {
    res.status(500).json({ message: "Failed to load sponsors" });
  }
});

// POST /api/student/sponsors/:id/request - student requests sponsorship from a sponsor
router.post("/student/sponsors/:id/request", requireStudent, async (req, res) => {
  try {
    const { id } = req.params;
    const { message = "" } = req.body || {};
    const sponsor = await Sponsor.findOne({ _id: id, active: true });
    if (!sponsor) return res.status(404).json({ message: "Sponsor not found" });

    // Prevent duplicates if already pledged or active
    const existing = await Sponsorship.findOne({ student: req.student._id, sponsor: sponsor._id, status: { $in: ["Pledged", "Active"] } });
    if (existing) {
      const reason = existing.status === "Active" ? "already sponsored" : "request already pending";
      return res.status(409).json({ message: `You are ${reason} with this sponsor.` });
    }

    const doc = await Sponsorship.create({
      student: req.student._id,
      sponsor: sponsor._id,
      amount: 0,
      currency: "INR",
      message: message?.slice(0, 280),
      status: "Pledged", // represents a sponsorship request
    });
    const populated = await doc.populate({ path: "sponsor", select: "name tier logoUrl" });
    res.status(201).json({ request: populated });
  } catch (_) {
    res.status(500).json({ message: "Failed to create request" });
  }
});

export default router;
